name = "spot-along-server"
main = "src/index.ts"
compatibility_date = "2024-05-10"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "DurableObjectRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DurableObjectRoom"]