name = "spot-along-auth"
main = "index.js"
compatibility_date = "2024-05-10"

# ADD THIS SECTION TO CREATE THE TEMPORARY TOKEN STORE
[[kv_namespaces]]
binding = "TOKEN_STORE"
id = "80fc25fb6db746458bad163a53d054d1" # Replace with actual ID from Cloudflare dashboard
preview_id = "80fc25fb6db746458bad163a53d054d1" # Replace with actual ID from Cloudflare dashboard

[env.production]
name = "spot-along-auth"

[env.staging]
name = "spot-along-auth-staging" 